// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dashOneUi

#ifndef UI_MAINPAGE_H
#define UI_MAINPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainPage
extern void ui_mainPage_screen_init(void);
extern void ui_mainPage_screen_destroy(void);
extern lv_obj_t * ui_mainPage;
extern lv_obj_t * ui_tempAux;
extern lv_obj_t * ui_tempCVT;
extern lv_obj_t * ui_indicatorPitch;
extern lv_obj_t * ui_idicatorRoll;
extern lv_obj_t * ui_angleRoll;
extern lv_obj_t * ui_anglePitch;
extern lv_obj_t * ui_timeCurrent;
extern lv_obj_t * ui_labelLapTime;
extern lv_obj_t * ui_timeCurrentLap;
extern lv_obj_t * ui_timeLastLap;
extern lv_obj_t * ui_timeBestLap;
extern lv_obj_t * ui_labelCurrent;
extern lv_obj_t * ui_labelLast;
extern lv_obj_t * ui_labelBest;
extern lv_obj_t * ui_statusLogging;
extern lv_obj_t * ui_statusGPS;
extern lv_obj_t * ui_statusRF;
extern lv_obj_t * ui_guageSpeed;
extern lv_obj_t * ui_iconCVTTemp;
extern lv_obj_t * ui_iconAuxTemp;
extern lv_obj_t * ui_guageTemperatire;
extern lv_obj_t * ui_speedWheel;
extern lv_obj_t * ui_speedGPS;
extern lv_obj_t * ui_indicatorSpeedGPS;
extern lv_obj_t * ui_indicatorSpeedWheel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

