// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dashOneUi

#ifndef _DASHONEUI_UI_H
#define _DASHONEUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_mainPage.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pitch75_png);    // assets/pitch75.png
LV_IMG_DECLARE(ui_img_roll75_png);    // assets/roll75.png
LV_IMG_DECLARE(ui_img_speedgage350_png);    // assets/speedGage350.png
LV_IMG_DECLARE(ui_img_tempcvtsmall_png);    // assets/tempCVTsmall.png
LV_IMG_DECLARE(ui_img_tempsmall_png);    // assets/tempSmall.png
LV_IMG_DECLARE(ui_img_vertical_temp_gauge_png);    // assets/vertical_temp_gauge.png
LV_IMG_DECLARE(ui_img_orangeneedlesmal_png);    // assets/orangeNeedleSmal.png
LV_IMG_DECLARE(ui_img_blueneedlesmall_png);    // assets/blueNeedleSmall.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
