// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dashOneUi

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_tempAux;
extern lv_obj_t * ui_tempCVT;
extern lv_obj_t * ui_indicatorPitch;
extern lv_obj_t * ui_indicatorRoll;
extern lv_obj_t * ui_angleRoll;
extern lv_obj_t * ui_anglePitch;
extern lv_obj_t * ui_timeCurrent;
extern lv_obj_t * ui_label01;
extern lv_obj_t * ui_timeCurrentLap;
extern lv_obj_t * ui_timeLastLap;
extern lv_obj_t * ui_timeBestLap;
extern lv_obj_t * ui_label02;
extern lv_obj_t * ui_label1;
extern lv_obj_t * ui_label2;
extern lv_obj_t * ui_statusLogging;
extern lv_obj_t * ui_statusGPS;
extern lv_obj_t * ui_statusRF;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_speedWheel;
extern lv_obj_t * ui_speedGPS;
extern lv_obj_t * ui_indicatorSpeedGPS;
extern lv_obj_t * ui_indicatorSpeedWheel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

