// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dashOneUi

#include "../ui.h"

lv_obj_t * ui_mainPage = NULL;
lv_obj_t * ui_tempAux = NULL;
lv_obj_t * ui_tempCVT = NULL;
lv_obj_t * ui_indicatorPitch = NULL;
lv_obj_t * ui_idicatorRoll = NULL;
lv_obj_t * ui_angleRoll = NULL;
lv_obj_t * ui_anglePitch = NULL;
lv_obj_t * ui_timeCurrent = NULL;
lv_obj_t * ui_labelLapTime = NULL;
lv_obj_t * ui_timeCurrentLap = NULL;
lv_obj_t * ui_timeLastLap = NULL;
lv_obj_t * ui_timeBestLap = NULL;
lv_obj_t * ui_labelCurrent = NULL;
lv_obj_t * ui_labelLast = NULL;
lv_obj_t * ui_labelBest = NULL;
lv_obj_t * ui_statusLogging = NULL;
lv_obj_t * ui_statusGPS = NULL;
lv_obj_t * ui_statusRF = NULL;
lv_obj_t * ui_guageSpeed = NULL;
lv_obj_t * ui_iconCVTTemp = NULL;
lv_obj_t * ui_iconAuxTemp = NULL;
lv_obj_t * ui_guageTemperatire = NULL;
lv_obj_t * ui_speedWheel = NULL;
lv_obj_t * ui_speedGPS = NULL;
lv_obj_t * ui_indicatorSpeedGPS = NULL;
lv_obj_t * ui_indicatorSpeedWheel = NULL;
// event funtions

// build funtions

void ui_mainPage_screen_init(void)
{
    ui_mainPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainPage, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempAux = lv_bar_create(ui_mainPage);
    lv_bar_set_range(ui_tempAux, 0, 250);
    lv_bar_set_value(ui_tempAux, 200, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_tempAux, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_tempAux, 20);
    lv_obj_set_height(ui_tempAux, 280);
    lv_obj_set_x(ui_tempAux, 287);
    lv_obj_set_y(ui_tempAux, -50);
    lv_obj_set_align(ui_tempAux, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_tempAux, LV_SCROLLBAR_MODE_OFF);

    lv_obj_set_style_bg_color(ui_tempAux, lv_color_hex(0xCE0A0A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempAux, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_tempCVT = lv_bar_create(ui_mainPage);
    lv_bar_set_range(ui_tempCVT, 0, 250);
    lv_bar_set_value(ui_tempCVT, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_tempCVT, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_tempCVT, 20);
    lv_obj_set_height(ui_tempCVT, 280);
    lv_obj_set_x(ui_tempCVT, 358);
    lv_obj_set_y(ui_tempCVT, -50);
    lv_obj_set_align(ui_tempCVT, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_tempCVT, lv_color_hex(0xCE0A0A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempCVT, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_indicatorPitch = lv_img_create(ui_mainPage);
    lv_img_set_src(ui_indicatorPitch, &ui_img_pitch75_png);
    lv_obj_set_width(ui_indicatorPitch, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_indicatorPitch, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_indicatorPitch, 50);
    lv_obj_set_y(ui_indicatorPitch, -160);
    lv_obj_set_align(ui_indicatorPitch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indicatorPitch, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_indicatorPitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_idicatorRoll = lv_img_create(ui_mainPage);
    lv_img_set_src(ui_idicatorRoll, &ui_img_roll75_png);
    lv_obj_set_width(ui_idicatorRoll, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_idicatorRoll, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_idicatorRoll, 150);
    lv_obj_set_y(ui_idicatorRoll, -160);
    lv_obj_set_align(ui_idicatorRoll, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_idicatorRoll, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_idicatorRoll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_angleRoll = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_angleRoll, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_angleRoll, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_angleRoll, 150);
    lv_obj_set_y(ui_angleRoll, -110);
    lv_obj_set_align(ui_angleRoll, LV_ALIGN_CENTER);
    lv_label_set_text(ui_angleRoll, "+0.0");
    lv_obj_set_style_text_color(ui_angleRoll, lv_color_hex(0xE8F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_angleRoll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_angleRoll, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_anglePitch = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_anglePitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_anglePitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_anglePitch, 50);
    lv_obj_set_y(ui_anglePitch, -110);
    lv_obj_set_align(ui_anglePitch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_anglePitch, "+0.0");
    lv_obj_set_style_text_color(ui_anglePitch, lv_color_hex(0xE8F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_anglePitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_anglePitch, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeCurrent = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_timeCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeCurrent, -262);
    lv_obj_set_y(ui_timeCurrent, -202);
    lv_obj_set_align(ui_timeCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeCurrent, "HH:mm:ss");
    lv_obj_set_style_text_color(ui_timeCurrent, lv_color_hex(0xE8F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeCurrent, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelLapTime = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_labelLapTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelLapTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelLapTime, 100);
    lv_obj_set_y(ui_labelLapTime, -35);
    lv_obj_set_align(ui_labelLapTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelLapTime, "Lap Times");
    lv_obj_set_style_text_color(ui_labelLapTime, lv_color_hex(0x6C858D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelLapTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelLapTime, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeCurrentLap = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_timeCurrentLap, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeCurrentLap, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeCurrentLap, 89);
    lv_obj_set_y(ui_timeCurrentLap, 20);
    lv_obj_set_align(ui_timeCurrentLap, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeCurrentLap, "mm:ss.ss");
    lv_obj_set_style_text_color(ui_timeCurrentLap, lv_color_hex(0xE8F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeCurrentLap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeCurrentLap, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLastLap = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_timeLastLap, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLastLap, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLastLap, 89);
    lv_obj_set_y(ui_timeLastLap, 70);
    lv_obj_set_align(ui_timeLastLap, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLastLap, "mm:ss.ss");
    lv_obj_set_style_text_color(ui_timeLastLap, lv_color_hex(0xE8F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLastLap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeLastLap, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeBestLap = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_timeBestLap, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeBestLap, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeBestLap, 89);
    lv_obj_set_y(ui_timeBestLap, 120);
    lv_obj_set_align(ui_timeBestLap, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeBestLap, "mm:ss.ss");
    lv_obj_set_style_text_color(ui_timeBestLap, lv_color_hex(0xE8F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeBestLap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeBestLap, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelCurrent = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_labelCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelCurrent, 224);
    lv_obj_set_y(ui_labelCurrent, 20);
    lv_obj_set_align(ui_labelCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelCurrent, "current");
    lv_obj_set_style_text_color(ui_labelCurrent, lv_color_hex(0x6C858D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelCurrent, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelLast = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_labelLast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelLast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelLast, 210);
    lv_obj_set_y(ui_labelLast, 70);
    lv_obj_set_align(ui_labelLast, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelLast, "last");
    lv_obj_set_style_text_color(ui_labelLast, lv_color_hex(0x6C858D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelLast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelLast, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelBest = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_labelBest, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelBest, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelBest, 215);
    lv_obj_set_y(ui_labelBest, 120);
    lv_obj_set_align(ui_labelBest, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelBest, "best");
    lv_obj_set_style_text_color(ui_labelBest, lv_color_hex(0x6C858D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelBest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelBest, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusLogging = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_statusLogging, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusLogging, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusLogging, 250);
    lv_obj_set_y(ui_statusLogging, 200);
    lv_obj_set_align(ui_statusLogging, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusLogging, "not-logging");
    lv_obj_set_style_text_color(ui_statusLogging, lv_color_hex(0x6C858D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusLogging, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusLogging, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusGPS = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_statusGPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusGPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusGPS, 21);
    lv_obj_set_y(ui_statusGPS, 203);
    lv_obj_set_align(ui_statusGPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusGPS, "GPS: unknown");
    lv_obj_set_style_text_color(ui_statusGPS, lv_color_hex(0x6C858D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusGPS, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusRF = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_statusRF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusRF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusRF, -200);
    lv_obj_set_y(ui_statusRF, 200);
    lv_obj_set_align(ui_statusRF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusRF, "RF: Not connected");
    lv_obj_set_style_text_color(ui_statusRF, lv_color_hex(0x6C858D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusRF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusRF, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_guageSpeed = lv_img_create(ui_mainPage);
    lv_img_set_src(ui_guageSpeed, &ui_img_speedgage350_png);
    lv_obj_set_width(ui_guageSpeed, LV_SIZE_CONTENT);   /// 350
    lv_obj_set_height(ui_guageSpeed, LV_SIZE_CONTENT);    /// 350
    lv_obj_set_x(ui_guageSpeed, -215);
    lv_obj_set_y(ui_guageSpeed, 0);
    lv_obj_set_align(ui_guageSpeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_guageSpeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_guageSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_iconCVTTemp = lv_img_create(ui_mainPage);
    lv_img_set_src(ui_iconCVTTemp, &ui_img_tempcvtsmall_png);
    lv_obj_set_width(ui_iconCVTTemp, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_iconCVTTemp, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_iconCVTTemp, 358);
    lv_obj_set_y(ui_iconCVTTemp, 143);
    lv_obj_set_align(ui_iconCVTTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconCVTTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconCVTTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_iconAuxTemp = lv_img_create(ui_mainPage);
    lv_img_set_src(ui_iconAuxTemp, &ui_img_tempsmall_png);
    lv_obj_set_width(ui_iconAuxTemp, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_iconAuxTemp, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_iconAuxTemp, 287);
    lv_obj_set_y(ui_iconAuxTemp, 143);
    lv_obj_set_align(ui_iconAuxTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconAuxTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconAuxTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_guageTemperatire = lv_img_create(ui_mainPage);
    lv_img_set_src(ui_guageTemperatire, &ui_img_vertical_temp_gauge_png);
    lv_obj_set_width(ui_guageTemperatire, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_guageTemperatire, LV_SIZE_CONTENT);    /// 300
    lv_obj_set_x(ui_guageTemperatire, 322);
    lv_obj_set_y(ui_guageTemperatire, -50);
    lv_obj_set_align(ui_guageTemperatire, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_guageTemperatire, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_guageTemperatire, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_speedWheel = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_speedWheel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedWheel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedWheel, -178);
    lv_obj_set_y(ui_speedWheel, 102);
    lv_obj_set_align(ui_speedWheel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedWheel, "27");
    lv_obj_set_style_text_color(ui_speedWheel, lv_color_hex(0xE8F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedWheel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedWheel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedGPS = lv_label_create(ui_mainPage);
    lv_obj_set_width(ui_speedGPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedGPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedGPS, -178);
    lv_obj_set_y(ui_speedGPS, 125);
    lv_obj_set_align(ui_speedGPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedGPS, "26");
    lv_obj_set_style_text_color(ui_speedGPS, lv_color_hex(0xE8F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedGPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedGPS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indicatorSpeedGPS = lv_img_create(ui_mainPage);
    lv_img_set_src(ui_indicatorSpeedGPS, &ui_img_orangeneedlesmal_png);
    lv_obj_set_width(ui_indicatorSpeedGPS, LV_SIZE_CONTENT);   /// 350
    lv_obj_set_height(ui_indicatorSpeedGPS, LV_SIZE_CONTENT);    /// 350
    lv_obj_set_x(ui_indicatorSpeedGPS, -215);
    lv_obj_set_y(ui_indicatorSpeedGPS, 0);
    lv_obj_set_align(ui_indicatorSpeedGPS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indicatorSpeedGPS, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_indicatorSpeedGPS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_indicatorSpeedGPS, -1250);

    ui_indicatorSpeedWheel = lv_img_create(ui_mainPage);
    lv_img_set_src(ui_indicatorSpeedWheel, &ui_img_blueneedlesmall_png);
    lv_obj_set_width(ui_indicatorSpeedWheel, LV_SIZE_CONTENT);   /// 350
    lv_obj_set_height(ui_indicatorSpeedWheel, LV_SIZE_CONTENT);    /// 350
    lv_obj_set_x(ui_indicatorSpeedWheel, -215);
    lv_obj_set_y(ui_indicatorSpeedWheel, 0);
    lv_obj_set_align(ui_indicatorSpeedWheel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indicatorSpeedWheel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_indicatorSpeedWheel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_indicatorSpeedWheel, -900);

}

void ui_mainPage_screen_destroy(void)
{
    if(ui_mainPage) lv_obj_del(ui_mainPage);

    // NULL screen variables
    ui_mainPage = NULL;
    ui_tempAux = NULL;
    ui_tempCVT = NULL;
    ui_indicatorPitch = NULL;
    ui_idicatorRoll = NULL;
    ui_angleRoll = NULL;
    ui_anglePitch = NULL;
    ui_timeCurrent = NULL;
    ui_labelLapTime = NULL;
    ui_timeCurrentLap = NULL;
    ui_timeLastLap = NULL;
    ui_timeBestLap = NULL;
    ui_labelCurrent = NULL;
    ui_labelLast = NULL;
    ui_labelBest = NULL;
    ui_statusLogging = NULL;
    ui_statusGPS = NULL;
    ui_statusRF = NULL;
    ui_guageSpeed = NULL;
    ui_iconCVTTemp = NULL;
    ui_iconAuxTemp = NULL;
    ui_guageTemperatire = NULL;
    ui_speedWheel = NULL;
    ui_speedGPS = NULL;
    ui_indicatorSpeedGPS = NULL;
    ui_indicatorSpeedWheel = NULL;

}
